// animals.js — Survival School animal database
// SS-031 — first 20 entries with full schema
// Single source of truth feeding: Deathmatch, I've Been Bit, Will You Eat It?
// Last updated: 2026-03-27

export const ANIMALS_DB = [
  {
    id: 'king_cobra',
    name: 'King cobra',
    scientific: 'Ophiophagus hannah',
    category: 'venomous_snake',
    lethality: 94,
    aggression: 72,
    speed: 65,
    size_kg: 9,
    venom_type: 'neurotoxic',
    antivenom_available: true,
    time_to_death_untreated_mins: 30,
    habitat: ['jungle', 'grassland', 'india', 'southeast_asia'],
    irwin_note: 'Steve had personal experience. Multiple times. None of this surprised him.',
    stevens_note: 'Has a spiritual connection with this animal specifically. The connection is not mutual.',
    oshea_note: 'Has written the definitive paper on Ophiophagus feeding behaviour. References chapter seven.',
    hales_note: 'Edible. Protein content solid. Would not recommend the acquisition method.',
    panel_comedy_trigger: 'stevens_communion'
  },
  {
    id: 'grizzly_bear',
    name: 'Grizzly bear',
    scientific: 'Ursus arctos horribilis',
    category: 'large_predator',
    lethality: 78,
    aggression: 62,
    speed: 72,
    size_kg: 272,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['mountain', 'forest', 'north_america', 'alaska'],
    irwin_note: 'Steve respected the grizzly. Considered it the supreme land predator in its range. Would have tried to pet one.',
    stevens_note: 'Was thinking about snakes during this entry. Has observations about snake encounters near grizzly habitat.',
    oshea_note: 'Chapter Fourteen. The play-dead protocol is statistically validated. Chapter Fourteen.',
    hales_note: 'Attacked twice by the same bear, the man just kept going. Have a look at that.',
    panel_comedy_trigger: 'bear_anecdote_guaranteed'
  },
  {
    id: 'great_white_shark',
    name: 'Great white shark',
    scientific: 'Carcharodon carcharias',
    category: 'aquatic_predator',
    lethality: 72,
    aggression: 55,
    speed: 78,
    size_kg: 1100,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['ocean', 'coastal', 'temperate', 'south_africa', 'australia'],
    irwin_note: 'Steve considered the great white the most misunderstood animal in the ocean. Was trying to get in the water with one.',
    stevens_note: 'Snakes are better. Has a prepared comparison. The comparison favours snakes.',
    oshea_note: 'The investigative bite theory: Chapter Eight. The shark is gathering information. Chapter Eight.',
    hales_note: 'Ate shark on the coast once. Other way around is less ideal. She\'ll be right.',
    panel_comedy_trigger: 'bear_surfing_anecdote'
  },
  {
    id: 'brazilian_wandering_spider',
    name: 'Brazilian wandering spider',
    scientific: 'Phoneutria fera',
    category: 'venomous_spider',
    lethality: 88,
    aggression: 92,
    speed: 42,
    size_kg: 0.006,
    venom_type: 'neurotoxic',
    antivenom_available: true,
    time_to_death_untreated_mins: 120,
    habitat: ['jungle', 'south_america', 'brazil', 'banana_shipments'],
    irwin_note: 'Steve encountered one in a banana crate in 1998. This is in his notes somewhere.',
    stevens_note: 'Not a snake. Stevens has opinions about things that are not snakes. These opinions are brief.',
    oshea_note: 'The venom causes involuntary sustained erection as a side effect. Mark has written about this. It is in his curriculum vitae.',
    hales_note: 'Banana. Not recommended. Have a look at that.',
    panel_comedy_trigger: 'oshea_curriculum_vitae'
  },
  {
    id: 'spotted_hyena',
    name: 'Spotted hyena',
    scientific: 'Crocuta crocuta',
    category: 'large_predator',
    lethality: 60,
    aggression: 82,
    speed: 60,
    size_kg: 68,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['savanna', 'africa', 'sub_saharan'],
    irwin_note: 'Steve was fascinated by hyena matriarchal structure. Wanted to document it. The hyenas were not cooperative.',
    stevens_note: 'Snakes have been found near hyena dens. Stevens has followed up on this.',
    oshea_note: 'The spotted hyena has a bite force of 1100 PSI. Chapter Eleven. The jaw is the point.',
    hales_note: 'Pack behaviour. Whole different calculation. Have a look at this.',
    panel_comedy_trigger: 'pack_assessment'
  },
  {
    id: 'komodo_dragon',
    name: 'Komodo dragon',
    scientific: 'Varanus komodoensis',
    category: 'venomous_reptile',
    lethality: 72,
    aggression: 65,
    speed: 35,
    size_kg: 70,
    venom_type: 'hemotoxic',
    antivenom_available: false,
    time_to_death_untreated_mins: 4320,
    habitat: ['island', 'indonesia', 'komodo', 'flores'],
    irwin_note: 'Steve filmed with Komodo dragons. Multiple times. He stayed slightly closer than anyone recommended.',
    stevens_note: 'A large monitor lizard. Stevens has a scale. The Komodo is high on it.',
    oshea_note: 'The venom glands in the lower jaw: controversial until 2009. Mark was right before 2009. It is in the paper.',
    hales_note: 'A bite won\'t kill you today. It\'ll kill you Thursday. That\'s the one to watch. Not too bad to look at though.',
    panel_comedy_trigger: 'delayed_mortality'
  },
  {
    id: 'cape_buffalo',
    name: 'Cape buffalo',
    scientific: 'Syncerus caffer',
    category: 'large_herbivore',
    lethality: 68,
    aggression: 85,
    speed: 60,
    size_kg: 700,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['savanna', 'forest', 'africa', 'sub_saharan'],
    irwin_note: 'Steve called the cape buffalo the most dangerous animal in Africa. He had reasons.',
    stevens_note: 'Was thinking about snakes. There are cape cobras in buffalo territory. Stevens has thoughts.',
    oshea_note: 'The Black Death. 200 human fatalities per year. Chapter Sixteen, the ungulate chapter. Yes, there is an ungulate chapter.',
    hales_note: 'Killed more hunters than any other animal in Africa. Have a look at that. She\'ll be right.',
    panel_comedy_trigger: 'black_death_nickname'
  },
  {
    id: 'saltwater_crocodile',
    name: 'Saltwater crocodile',
    scientific: 'Crocodylus porosus',
    category: 'aquatic_predator',
    lethality: 82,
    aggression: 88,
    speed: 32,
    size_kg: 450,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['coastal', 'estuarine', 'australia', 'southeast_asia', 'india'],
    irwin_note: 'Steve wrestled saltwater crocodiles on television. This was the job. He considered it a reasonable job.',
    stevens_note: 'Not a snake. However: saltwater crocodiles and sea snakes share habitat. Stevens has a pivot prepared.',
    oshea_note: 'The death roll: 2,500 PSI bite force, then rotation. Chapter Nine. Do not attempt to out-rotate it.',
    hales_note: 'Northern Australia. Have a look at that. The Aboriginal people don\'t swim in those parts. There\'s a reason.',
    panel_comedy_trigger: 'irwin_wrestling_reference'
  },
  {
    id: 'siberian_tiger',
    name: 'Siberian tiger',
    scientific: 'Panthera tigris altaica',
    category: 'large_predator',
    lethality: 80,
    aggression: 55,
    speed: 78,
    size_kg: 300,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['taiga', 'forest', 'russia', 'china', 'far_east'],
    irwin_note: 'Steve considered the tiger the most beautiful predator on earth. Had strong feelings about its conservation status.',
    stevens_note: 'The Amur tiger overlaps with the Amur leopard. Stevens once tracked both simultaneously. The snakes were better.',
    oshea_note: 'Ambush specialist. 30-foot launch from standing. Chapter Five, the felid chapter. The jump is the key data point.',
    hales_note: 'Biggest cat alive. Have a look at that. She\'ll be right from a considerable distance.',
    panel_comedy_trigger: 'conservation_sidebar'
  },
  {
    id: 'hippopotamus',
    name: 'Hippopotamus',
    scientific: 'Hippopotamus amphibius',
    category: 'large_herbivore',
    lethality: 65,
    aggression: 92,
    speed: 50,
    size_kg: 1800,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['river', 'lake', 'sub_saharan_africa'],
    irwin_note: 'Steve called hippos the most underestimated animal in Africa. He had a theory. The theory was correct.',
    stevens_note: 'Snakes are common in hippo territory. River systems. Stevens is aware of this and grateful for it.',
    oshea_note: 'The blood-red sweat is not sweat. It is a natural sunscreen and antibiotic. Chapter Twelve. It looks like blood. It is not blood.',
    hales_note: 'Kills more people in Africa than any other animal except mosquitoes. Have a look at that. Nobody expects it.',
    panel_comedy_trigger: 'bloodsweat'
  },
  {
    id: 'box_jellyfish',
    name: 'Box jellyfish',
    scientific: 'Chironex fleckeri',
    category: 'venomous_marine',
    lethality: 96,
    aggression: 8,
    speed: 8,
    size_kg: 2,
    venom_type: 'cardiotoxic',
    antivenom_available: true,
    time_to_death_untreated_mins: 5,
    habitat: ['ocean', 'coastal', 'australia', 'indo_pacific'],
    irwin_note: 'Steve was aware of box jellyfish and maintained appropriate distance. One of the few animals where he stood back.',
    stevens_note: 'Not a snake. Sea snakes share this water. Stevens notes the irony of the jellyfish being more dangerous.',
    oshea_note: 'Most venomous marine animal known. 60 nematocysts per square centimetre of tentacle. Chapter Twenty-Two. Do not rub the tentacles.',
    hales_note: 'You\'ve got about five minutes. Have a look at that. Aboriginal people have known about these waters for 40,000 years.',
    panel_comedy_trigger: 'five_minute_window'
  },
  {
    id: 'blue_ringed_octopus',
    name: 'Blue-ringed octopus',
    scientific: 'Hapalochlaena lunulata',
    category: 'venomous_marine',
    lethality: 97,
    aggression: 30,
    speed: 12,
    size_kg: 0.08,
    venom_type: 'tetrodotoxin',
    antivenom_available: false,
    time_to_death_untreated_mins: 20,
    habitat: ['ocean', 'tidal_pools', 'australia', 'indo_pacific'],
    irwin_note: 'Steve once picked one up before he knew what it was. This is in his early field notes. He was twenty-two.',
    stevens_note: 'The blue-ringed octopus and the banded sea krait are found in similar habitat. Stevens has a ranking.',
    oshea_note: 'No antivenom exists. Tetrodotoxin blocks sodium channels. Manual ventilation is the only treatment. Chapter Twenty-Three. The chapter ends quickly.',
    hales_note: 'Fits in your hand. Will kill you in twenty minutes. No treatment available. Have a look at that.',
    panel_comedy_trigger: 'no_antivenom_exists'
  },
  {
    id: 'inland_taipan',
    name: 'Inland taipan',
    scientific: 'Oxyuranus microlepidotus',
    category: 'venomous_snake',
    lethality: 98,
    aggression: 35,
    speed: 68,
    size_kg: 1.5,
    venom_type: 'neurotoxic',
    antivenom_available: true,
    time_to_death_untreated_mins: 45,
    habitat: ['desert', 'semi_arid', 'australia', 'outback'],
    irwin_note: 'Steve had deep respect for the inland taipan. Considered it the purest expression of evolutionary lethality.',
    stevens_note: 'The most toxic snake venom on earth. By a significant margin. Stevens is visibly moved discussing this.',
    oshea_note: 'LD50 of 0.025 mg/kg. One strike contains enough venom to kill 100 humans. Chapter One. It is Chapter One because it must be.',
    hales_note: 'Most venomous snake in the world. Lives in the middle of Australia. Has the good sense to avoid people. Have a look at that.',
    panel_comedy_trigger: 'chapter_one'
  },
  {
    id: 'polar_bear',
    name: 'Polar bear',
    scientific: 'Ursus maritimus',
    category: 'large_predator',
    lethality: 85,
    aggression: 80,
    speed: 65,
    size_kg: 550,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['arctic', 'sea_ice', 'norway', 'canada', 'russia'],
    irwin_note: 'Steve never documented polar bears. Would have. Had plans. The conservation angle concerned him.',
    stevens_note: 'Cold-weather snakes exist. Stevens is aware the polar bear encounter would have limited snake cross-reference.',
    oshea_note: 'The only bear that actively hunts humans. It is not territorial aggression. It is predation. Chapter Three. Important distinction.',
    hales_note: 'The only animal in the world that will stalk you. Down wind. Patiently. Have a look at that.',
    panel_comedy_trigger: 'active_predation'
  },
  {
    id: 'bull_shark',
    name: 'Bull shark',
    scientific: 'Carcharhinus leucas',
    category: 'aquatic_predator',
    lethality: 70,
    aggression: 82,
    speed: 72,
    size_kg: 230,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['ocean', 'coastal', 'estuary', 'river', 'worldwide'],
    irwin_note: 'Steve considered the bull shark the most dangerous shark in practice. Not the most dramatic — the most dangerous.',
    stevens_note: 'Bull sharks have been found 4,000km up the Amazon. With the snakes. Stevens considers this habitat overlap significant.',
    oshea_note: 'Highest testosterone of any animal measured. More aggressive than the great white in close quarters. Chapter Eight, appendix.',
    hales_note: 'Can live in fresh water. Up rivers. In the Murray-Darling basin. Have a look at that.',
    panel_comedy_trigger: 'river_shark'
  },
  {
    id: 'honey_badger',
    name: 'Honey badger',
    scientific: 'Mellivora capensis',
    category: 'small_predator',
    lethality: 28,
    aggression: 99,
    speed: 42,
    size_kg: 14,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['savanna', 'grassland', 'forest', 'africa', 'india', 'middle_east'],
    irwin_note: 'Steve admired the honey badger unreservedly. No qualifications. The honey badger does not have qualifications either.',
    stevens_note: 'The honey badger eats cobras for breakfast. Literally. It has partial immunity to neurotoxic venom. Stevens has feelings about this.',
    oshea_note: 'Documented eating king cobras, puff adders, and black mambas. Partial venom immunity confirmed. Chapter Seventeen. The chapter is admiring in register.',
    hales_note: 'The most fearless animal in the world. Guinness World Record. Will attack a lion. Not recommended but documented.',
    panel_comedy_trigger: 'maximum_aggression_minimum_mass'
  },
  {
    id: 'black_mamba',
    name: 'Black mamba',
    scientific: 'Dendroaspis polylepis',
    category: 'venomous_snake',
    lethality: 97,
    aggression: 88,
    speed: 82,
    size_kg: 1.6,
    venom_type: 'neurotoxic',
    antivenom_available: true,
    time_to_death_untreated_mins: 20,
    habitat: ['savanna', 'woodland', 'africa', 'sub_saharan'],
    irwin_note: 'Steve had deep respect for the black mamba. Called it the most dangerous snake encounter achievable. This is high praise from Steve.',
    stevens_note: 'The black mamba. Stevens has prepared remarks. The remarks are extensive. There is a ranking at the end. The mamba is high.',
    oshea_note: 'Fastest snake on earth. 20km/h over short distance. Two-drop mortality: two drops of venom, untreated, is sufficient. Chapter Two. It is Chapter Two for a reason.',
    hales_note: 'Fastest land snake in the world. Highly aggressive when cornered. Attacks repeatedly. Have a look at that.',
    panel_comedy_trigger: 'two_drop_mortality'
  },
  {
    id: 'cassowary',
    name: 'Cassowary',
    scientific: 'Casuarius casuarius',
    category: 'large_bird',
    lethality: 55,
    aggression: 72,
    speed: 60,
    size_kg: 58,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['rainforest', 'australia', 'new_guinea', 'queensland'],
    irwin_note: 'Steve documented cassowaries in Queensland. Maintained appropriate distance. The cassowary was not the animal Steve got closest to. This is notable.',
    stevens_note: 'Not a snake. The cassowary and the amethystine python share habitat in Queensland. Stevens pivots smoothly.',
    oshea_note: 'The inner toe claw: 12cm. The kick: capable of disembowelment. Chapter Eighteen. The cassowary is underrated in Chapter Eighteen.',
    hales_note: 'Most dangerous bird in the world. Queensland. They\'re about. Have a look at that and don\'t run.',
    panel_comedy_trigger: 'disembowelment_claw'
  },
  {
    id: 'swan',
    name: 'Swan',
    scientific: 'Cygnus olor',
    category: 'bird',
    lethality: 5,
    aggression: 95,
    speed: 25,
    size_kg: 12,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['river', 'lake', 'park', 'uk', 'europe'],
    irwin_note: 'Steve never documented the mute swan in detail. Would have found the aggression-to-lethality ratio philosophically interesting.',
    stevens_note: 'The mute swan is not a snake. Stevens has almost nothing to add. He considers the aggression data personally offensive.',
    oshea_note: 'The mute swan can break a human arm. This is widely reported. The evidence base is not strong. Mark notes this. Chapter Twenty-Four. The chapter is two pages.',
    hales_note: 'Can break your arm. Or so they say. Have a look at that. She\'ll be right. Probably.',
    panel_comedy_trigger: 'arm_breaking_mythology'
  },
  {
    id: 'wolverine',
    name: 'Wolverine',
    scientific: 'Gulo gulo',
    category: 'small_predator',
    lethality: 40,
    aggression: 96,
    speed: 48,
    size_kg: 18,
    venom_type: null,
    antivenom_available: false,
    time_to_death_untreated_mins: null,
    habitat: ['boreal_forest', 'tundra', 'north_america', 'scandinavia', 'russia'],
    irwin_note: 'Steve expressed genuine respect for the wolverine. "Pound for pound, the most tenacious animal on earth." He was not wrong.',
    stevens_note: 'Cold-weather environment. Limited snake overlap. Stevens notes this with mild disappointment.',
    oshea_note: 'Has driven bears from kills. Documented cases: grizzly, black bear, polar bear. 18 kilograms versus 272 kilograms. Chapter Seventeen has a table.',
    hales_note: 'Will take on a bear over a carcass and win. 18 kilos. Have a look at that. Not indigenous to Australia. We have better.',
    panel_comedy_trigger: 'bear_displacement'
  }
];

// Lookup helper — matches by name (case-insensitive)
export function lookupAnimal(name) {
  if (!name) return null;
  const n = name.toLowerCase().trim();
  return ANIMALS_DB.find(a => a.name.toLowerCase() === n) || null;
}
